# Generated by Django 3.2.4 on 2021-06-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210617_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('H', 'High Priority'), ('M', 'Medium Priority'), ('L', 'Low Priority')], max_length=2),
        ),
    ]
